name: IMDb Auto DB Updater

on:
  schedule:
    - cron: '0 0 * * 0' # Her Pazar saat 00:00'da otomatik çalışır
  workflow_dispatch: # Manuel tetikleme butonu ekler

permissions:
  contents: write # GitHub Releases'e dosya yükleyebilmek için gerekli izin

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Depoyu Klonla
      uses: actions/checkout@v4

    - name: Python Kurulumu
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Veritabanını Dönüştür
      run: python convert.py

    - name: Güncel Tarih Bilgisi Al
      id: date
      run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

    - name: Hazır DB Dosyasını GitHub Releases'e Yükle
      uses: softprops/action-gh-release@v2
      with:
        files: imdb_complete.db
        tag_name: v-${{ steps.date.outputs.date }}
        name: IMDb Database (${{ steps.date.outputs.date }})
        body: |
          Enigma2 için otomatik üretilmiş güncel IMDb veritabanı.
          Oluşturulma Tarihi: ${{ steps.date.outputs.date }}
